<div class="intro">
    <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
        <h1>Welcome !</h1>
        <p><i>"Customer service shouldn't just be a department, it should be the entire company."</i></p>
        <p>-&nbsp; <i>Elizabeth Fitzpatrick, Founder and CEO</i></p>

        <a class="button" href="<?php echo $this->getUrl('') ?>membership/account/create/"> Let&rsquo;s Get Started Button</a>
        <p class="alrdyMember">Already a Member? <a href="<?php echo $this->getUrl('') ?>membership/account/login/">Click Here</a></p>

    <?php else: ?> 
        <h1>Welcome Back <?php echo Mage::getSingleton('customer/session')->getCustomer()->getName(); ?> !</h1>

        <p><i>"Customer service shouldn't just be a department, it should be the entire company."</i></p>
        <p>-&nbsp; <i>Elizabeth Fitzpatrick, Founder and CEO</i></p>

        <a class="button" href="<?php echo $this->getUrl('') ?>my-closet.html">SCHEDULE A PICKUP</a> <a class="button" href="<?php echo $this->getUrl('') ?>my-closet.html">SCHEDULE A DELIVERY</a>
    <?php endif; ?>
</div>
<div class="flexslider carousel">
    <ul class="slides">
        <li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/slider/1Shopping_Bags.jpg" /></li>
        <li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/slider/2Red_Coat.jpg" /></li>
        <li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/slider/3White_Coat.jpg" /></li>
        <li><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/slider/Papers.jpg" /></li>

    </ul>
</div>
<div class="contentWrapper">
    <div class="middleHead">
        <div class="line">&nbsp;</div>
        <h3>Services</h3>
    </div>
    <div class="container">
        <div class="row homeGrid">
            <div class="col-md-3 col-sm-6">
                <p><b>Extend and Declutter</b></p>
                <p>Do you have enough closet space? If you&rsquo;re like most of us the answer is no. My Closet Concierge allows you to have the easily accessible and viewable closet of your dreams, perfectly organized and available at a moments notice.</p>
                <a  href="<?php echo $this->getUrl('') ?>services/#open_here1">Learn More</a></div>
            <div class="col-md-3 col-sm-6 brdr brdr-sm-r_0">
                <p><b>Seasonal Storage</b></p>
                <p>No longer take up half your closet with winter coats when it&rsquo;s 100 degrees outside. Let us take care of it for you. We store your clothes and accessories in top of the line conditions.</p>
                <a  href="<?php echo $this->getUrl('') ?>services#open_here2">Learn More</a></div>
            <div class="col-md-3 col-sm-6 brdr l_0">
                <p><b>Luggage Free Travel</b></p>
                <p>Never again deal with hassle of lugging baggage through the airport. With luggage free travel your items will be delivered directly to your hotel in ready to wear condition.</p>
                <a  href="<?php echo $this->getUrl('') ?>services#open_here3">Learn More</a></div>
            <div class="col-md-3 col-sm-6">
                <p><b>Dry Cleaned and Ready to Go</b></p>
                <p>Never again worry if you remembered to have that dress cleaned before your big event.&nbsp; Your items will always be dry cleaned and ready to go when you are.</p>
                <a href="<?php echo $this->getUrl('') ?>services#open_here4">Learn More</a></div>
        </div>
    </div>
</div>