
<div class='fieldset'>
    <h2 class="legend">Make Payment</h2>
    


    <?php
    $exp = explode('-', $this->getChosenplan());
    
    ?>
<div id="previous_membership" >
   <?php  if(empty($exp[1])) { ?>
    <?php echo $this->__('You Chose'); ?>
    <h3 style="color: #e76200;"><?php echo "I wish to pay later"; ?></h3>
  
    <h2 style="color: #e76200;"><?php echo "0 USD"; ?></h2>
   <?php } else {?>
         <?php echo $this->__('You Chose'); ?>
    <h3 style="color: #e76200;"><?php echo $exp[1]; ?></h3>
    <?php echo $this->__('Amount to be paid'); ?>
    <h2 style="color: #e76200;"><?php echo $exp[0] . " USD"; ?></h2>
  <?php  } ?>
    </div>
    <?php
    $var = $this->getSettings();
    $gateurl = $var['a'];
    $api_login_id = $var['b'];
    $transaction_key = $var['d'];
    $amount = $exp[0];
    $mem_table_id =  $exp[2];
    ?>

    <form method="post" action="<?php echo Mage::getBaseUrl(); ?>membership/payment/authorizepayment/">
        <div class="form-list">
         <?php   $model = Mage::getModel('customer/customer')->load(Mage::getSingleton('customer/session')->getMemId());
            $memtypeid = $model->getMemType();
             if ($memtypeid === '0') { ?>
             <li class="fields">
                    <div class="field">
                        <label for="membership_plan" class="required"><?php echo $this->__('Choose your membership type') ?><em>*</em></label>
                        <div class="input-box">

                              <?php
                                                $model = Mage::getModel('membership/types');
                                                $data = $model->getCollection()->getData();
                                                foreach ($data as $options) {
                                                    ?>
                            <input type="radio" name="mem_type" value="<?php echo $options['membership_id']; ?>" onclick="javascript:GetPrice(this.value);" />&nbsp;<?php echo $options['membership_type']; ?><br>
                                                <?php } ?>
                        </div>
                    </div>
                    <div class="field">
                        <label for="membership_plan" class="required"><?php echo $this->__('Membership price') ?></label>

                        <div class="input-box" style="font-size: 15px;">
                            <?php echo "&nbsp; " . Mage::app()->getStore()->getCurrentCurrencyCode(); ?>

                            <div id="price_change" style="float: left;">
                              <?php echo $this->__('0') ?> <!-- amount here -->
                            </div>    
                            <input type="hidden" name="amt" id="mem_amt" value=" <?php echo $this->__('0') ?>"/>
                           
                       </div>
                  </div>
                    
               
                </li>
               

           <?php } else { ?>
            <input type="hidden" name="mem_type" value="<?php echo $exp[1]; ?>" />
            <input type="hidden" name="amt" value="<?php echo $amount; ?>" />
            <input type="hidden" name="mem_table_id" value="<?php echo $mem_table_id; ?>" />
               <?php } ?>
            <div>
                <label for="card_number">Credit Card Number</label>
                <div class="input-box">
                    <input type="text" class="input-text"  name="x_card_num" value=""></input>
                </div>
            </div>

            <div>       
                <label for="exp">Card Expiry date</label><br>

<!--                    <input type="text" class="input-text" size="4" name="x_exp_date" value=""></input>-->
                <select name="card_exp_year" style="width: 10%">
                    <?php
                    for ($ye = date("Y"); $ye <= date("Y") + 20; $ye++) {
                        echo "<option value='$ye'>$ye</option>";
                    }
                    ?> 

                </select> 

                <select name="card_exp_month" style="width:7%;">
                    
                    <option value="01">01</option>
                    <option value="02">02</option>
                    <option value="03">03</option>
                    <option value="04">04</option>
                    <option value="05">05</option>
                    <option value="06">06</option>
                    <option value="07">07</option>
                    <option value="08">08</option>
                    <option value="09">09</option>
                    <?php
                    for ($mo = 10; $mo <= 12; $mo++)
                       echo "<option value='$mo'>$mo</option>";
                    ?>
                </select>

            </div>
            <div>
                <label for="CVV">CVV</label>
                <div class="input-box">
                    <input type="text" class="input-text" size="4" name="x_card_code" value=""></input>
                </div>
            </div>


            <div class="fields">
                <div class="field">
                    <label for="First Name">First Name</label>
                    <div class="input-box">
                        <input type="text" class="input-text" size="15" name="x_first_name" value="<?php echo Mage::getSingleton('customer/session')->getMemFname(); ?>" readonly></input>

                    </div>
                </div>
                <div class="field">
                    <label for="Last Name">Last Name</label>

                    <div class="input-box">
                        <input type="text" class="input-text" size="14" name="x_last_name" value="<?php echo Mage::getSingleton('customer/session')->getMemLname(); ?>" readonly></input>

                    </div>
                </div>
            </div>

        </div>

        <div class="buttons-set">

            <button type="submit" title="Submit" class="button"><span><span>Submit</span></span></button>
        </div>
    </form>






</div>
<script type="text/javascript">
    function GetPrice(memid)
    {
 $('previous_membership').hide();
 
        new Ajax.Request('<?php echo Mage::getBaseUrl() . "membership/payment/Getprice?memid=" ?>' + memid,
                {
                    method: "get",
                    onSuccess: function (transport) {
                        var response = transport.responseText || "no response text";
                        node = $("price_change");
                        //$("price_change").update = response;
                        node.update(response);
  $('mem_amt').writeAttribute('value', response);
                    },
                    onFailure: function () {
                        alert("Something went wrong...")
                    }
                });


    }
</script>








<div class="buttons-set">
    <p class="back-link"><a onclick="goBack()" class="back-link"><small>&laquo;Back</small></a></p>
</div>
<script>
    function goBack() {
        window.history.back();
    }
</script>