
<div class="row">
    <div class="subhead">
<h2 style="text-align: center;">Pick Up Information</h2>
</div>
    <form action="" method="post">
           <label for="email"> Select Category List: </label></br>                 
            <?php
            $cat = Mage::getModel('catalog/category')->load(16);
            $subcats = $cat->getChildren();
            $all_sub_cat = explode(',', $subcats);
            foreach ($all_sub_cat as $cat_id) {
                $category = Mage::getModel('catalog/category')->load($cat_id);
                ?>     
           <div class="form-group col-md-4">                               
                <img src="<?php echo Mage::getBaseUrl('media') . 'catalog/category/' . $category->image; ?>" alt=""/><br>
                <div class="checkbox">
                    <label style="text-align: center; margin-right: 10px;"><input type="checkbox" name="categoryname" value="<?php echo $category->getId(); ?>"> <?php echo $category->name; ?></label>
                </div></br></div>  
            <?php } ?>
          
        <div class="form-group ">
            <label for="comment">Comment:</label>
            <textarea class="form-control" rows="5" name="comment" value="" id="comment"></textarea>
        </div>
           <input type="submit" class="button" value="<?php echo $this->__('Pick Me Up') ?>"/>
<!--        <button  class="button" title="<?php // echo $this->__('Pick Me Up') ?>"  ></button>  -->
    </form>
</div>
