


<div class="row myBag">
    <div class="subhead">
        <h2 style="text-align: center;"><?php echo $this->__('Pick Up Information') ?></h2>
    </div>
    <form action="" method="post">
        <div class="col-md-12 dataTable">
            <div class="row th">
                <div class="col-xs-4">Select Category</div>
                <div class="col-xs-6">Category </div>
                <div class="col-xs-2">Quantity </div>

            </div>
            <?php
            $cat = Mage::getModel('catalog/category')->load(16);
            $subcats = $cat->getChildren();
            $all_sub_cat = explode(',', $subcats);
            foreach ($all_sub_cat as $cat_id) {
                $category = Mage::getModel('catalog/category')->load($cat_id);
                $image = Mage::getBaseUrl('media') . 'catalog/category/' . $category->image;
                ?> 
                <div class="row">
                    <div class="col-xs-1">
                        <input type="checkbox" name="categoryname[<?php echo $category->getId(); ?>]" id="categoryid" value="<?php echo $category->getId(); ?>">
                    </div>                            
                    <div class="col-xs-3">
                        <div class="thumb">
                            <img src="<?php echo $image; ?>" width="75" height="75" alt="<?php echo $category->name; ?>"/><br>
                        </div>
                    </div>
                    <div class="col-xs-6">
                        <?php echo $category->name; ?>           
                    </div>                                
                    <div class="col-xs-2">
                        <input type="text" id="quantity" title="quantity" name="quantity[<?php echo $category->getId(); ?>]" value="" class="input-text qty">
                    </div>

                </div><?php } ?>
            <div class="row th foot">
                <div class="col-xs-12">
                    <textarea class="form-control" rows="3" id="comment" class="input-text" placeholder="Comment" name="comment" value="" ></textarea>  
                    <input type="submit"  class="button pull-right pickupinfo " value="<?php echo $this->__('Pick Me Up') ?>"/> 
                </div>
            </div>

        </div>
    </form>
</div>
