<?php
$cat = Mage::getModel('catalog/category')->load(16);
$subcats = $cat->getChildren();
$all_sub_cat = explode(',', $subcats);
?>
<div class="row">
    <?php

    $hide_pickup = false;
    foreach ($all_sub_cat as $cat_id) {
        $userid = Mage::getSingleton('customer/session')->getId();
        $category = Mage::getModel('catalog/category')->load($cat_id);
        $categories = Mage::getModel('catalog/category')->load($category->getId())
                ->getProductCollection()
                ->addAttributeToSelect('entity_id')
                ->addAttributeToFilter('status', 1)
                ->addAttributeToFilter('visibility', 4);
        $products = Mage::getModel('catalog/product')
                ->getCollection()
                ->addAttributeToFilter('customer_name', $userid)
                ->addCategoryFilter($category)
                ->load();
        if(!Mage::getSingleton('customer/session')->isLoggedIn() && ($categories->count() > 0 ) ){
     $hide_pickup = true;?>
              <div class="col-sm-4 itemList">
                    <a href="<?php echo $category->url_path; ?>">
                        <img src="<?php echo Mage::getBaseUrl('media') . 'catalog/category/' . $category->image; ?>" alt=""/>
                        <b><?php echo $category->name; ?></b>
                    </a>
                </div>
   <?php     }
        foreach ($products as $product) {
            $customerid = $product->getCustomerName();
            if (($categories->count() > 0 ) && ($products->count() > 0)) {
                $hide_pickup = true;
                ?>
                <div class="col-sm-4 itemList">
                    <a href="<?php echo $category->url_path; ?>">
                        <img src="<?php echo Mage::getBaseUrl('media') . 'catalog/category/' . $category->image; ?>" alt=""/>
                        <b><?php echo $category->name; ?></b>
                    </a>
                </div>
            <?php
            }
        }
    }

    if(!$hide_pickup && (!Mage::getSingleton('customer/session')->isLoggedIn()))
    {
                
                ?>
                <div class="alignCenter">
                    <a class="button" href="http://localhost/mgn/magento/mycloset/pickup"> Pick up my clothing</a>
                </div>
                <?php
            
    }
    ?>
</div>